name: Update dist files on 

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.SECRETS_AWS_ROLE_TO_ASSUME }}
        aws-region: us-west-2
    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync --exclude "*" --include "index.html" --include "error.html" --include "assets/*" . s3://blusol-landing-page

        # Invalidate Cloudfront
    - name: Cloudfront Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.SECRETS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"